#pragma once
#include <cstdint>
#include <string>

// THE DYE: one colour, carried by an item, applied to a worn garment's art at
// shade time.
//
// WHAT PROBLEM THIS SOLVES. A village needs forty outfits. Authoring forty is
// not the answer and neither is authoring one and accepting that everybody
// matches. So the art and the colour are split: assets/items/{tunic,trousers,
// shoes,...} are GREYSCALE WEAVES generated by scripts/gen_peasant_clothes.py,
// where every cell's value is a MULTIPLIER, and the colour that multiplier
// applies to arrives at runtime as one word. Nine patterns times any colour is
// as much variety as anybody is going to look at, for nine pieces of art.
//
// WHY PER-INSTANCE AND NOT PER-PALETTE. The obvious alternative is to allocate
// art-palette slots per dye and bake the colour into the voxels. It would cost
// nothing at shade time and it has a hard ceiling: the merged art palette is
// 255 entries TOTAL across every prefab in the game (sim/microbody.h
// artColors, world.h kArtPaletteSlotsGpu), shared with every creature's skin,
// so a six-tone garment ramp buys about forty simultaneous colours before
// somebody's face goes unpainted. It would also mean a COW brick per dyed
// garment. The instance word has neither limit: the colour is continuous, and
// two hundred differently-dressed villagers share nine bricks.
//
// WHERE IT RIDES. sim/microbody.h MicroBodyInstGpu's fourth word — which was
// padding, is already uploaded, and is documented there as carrying nothing.
// The struct must stay 16 bytes (its static_assert is the only mechanical
// guard the CPU/WGSL pair has), so a spare word is the only place a new
// per-instance value can go at all.
//
// THE ENCODING. Bit 24 is the FLAG and the low 24 bits are the colour in the
// same byte order `unpackColor` reads (r low), so the shader unpacks a dye
// with the function it already has. Zero means UNDYED, which is what every
// existing caller passes and what debris, old saves and every non-garment keep
// passing — so "no dye" costs no branch anywhere and an undyed linen shirt
// renders as the neutral grey cloth it literally is, rather than as black.
//
// A DYE IS NOT A MATERIAL. It does not change what the cloth is, what it
// weighs, how it burns or what acid does to it — it is paint, in exactly the
// sense gen_stock_armor.py means when it says colour is art. Nothing in the
// sim reads it and it is never hashed (CLAUDE.md rule 1); it travels in saves
// only because losing the colour of your own shirt across a reload would be a
// bug the player notices immediately.

// Set on a packed dye word to distinguish "black" from "no dye". Without it a
// dye of (0,0,0) is indistinguishable from the default, and the failure mode is
// a garment that silently refuses to be dyed black.
constexpr uint32_t kDyeFlag = 1u << 24;

// Pack 0..1 floats. Values outside the range are clamped rather than wrapped:
// a colour picker that hands back 1.0001 should give white, not black.
inline uint32_t DyePack(float r, float g, float b) {
  auto q = [](float v) -> uint32_t {
    const float c = v < 0.0f ? 0.0f : (v > 1.0f ? 1.0f : v);
    return (uint32_t)(c * 255.0f + 0.5f);
  };
  return kDyeFlag | q(r) | (q(g) << 8) | (q(b) << 16);
}

inline bool DyeSet(uint32_t dye) { return (dye & kDyeFlag) != 0; }

inline void DyeUnpack(uint32_t dye, float* rgb) {
  rgb[0] = (float)(dye & 0xFFu) / 255.0f;
  rgb[1] = (float)((dye >> 8) & 0xFFu) / 255.0f;
  rgb[2] = (float)((dye >> 16) & 0xFFu) / 255.0f;
}

// ---- THE REFERENCE TONE -----------------------------------------------------
//
// The garment art's BASE grey, 0.70, as a fraction. A cell painted at exactly
// this value renders as exactly the picked colour; a weave tone at 0.55 renders
// at 0.79 of it, a seam at 0.29 renders at 0.41 of it, and so on. That is the
// whole shading model and it is one divide.
//
// STATED IN THREE PLACES AND CHECKED IN TWO. `DYE_REF` in
// assets/shaders/microbody.wgsl is what the GPU uses; `DYE_REF_GREY` in
// scripts/gen_peasant_clothes.py is what the art is authored against and
// asserts against its own ramp; this is what the UI previews with. A
// disagreement is not a crash — it is every dyed garment in the game coming
// out uniformly too bright or too dark, with the cause two files away — so the
// items gate compares this against the shader's literal.
constexpr float kDyeRef = 0.70f;

// What a cell painted at grey `g` (0..1) looks like once dyed. The UI's swatch
// and the shader must agree about this or the colour you pick is not the colour
// you get; keeping it as a named function is what makes the gate able to ask.
inline float DyeToneMul(float grey) { return grey / kDyeRef; }

// HSV -> RGB, 0..1 all round. Here rather than reaching for ImGui's version
// because the caller is the frame loop, not the overlay: a "random colour"
// button is game logic that happens to be triggered from a panel, and pulling
// imgui.h into main.cpp's tick block for one conversion would be the wrong
// direction for a file that deliberately does not know the UI exists.
//
// WHY THE RANDOM BUTTON GOES THROUGH HSV AT ALL: a uniform point in the RGB
// cube is overwhelmingly a desaturated brown. Picking a hue and then a
// generous saturation is what makes "random" produce clothes rather than mud.
inline void DyeFromHsv(float h, float s, float v, float* rgb) {
  h = h - (float)(int)h;
  if (h < 0.0f) h += 1.0f;
  const float i = (float)(int)(h * 6.0f);
  const float f = h * 6.0f - i;
  const float p = v * (1.0f - s);
  const float q = v * (1.0f - f * s);
  const float t = v * (1.0f - (1.0f - f) * s);
  switch ((int)i % 6) {
    case 0: rgb[0] = v; rgb[1] = t; rgb[2] = p; break;
    case 1: rgb[0] = q; rgb[1] = v; rgb[2] = p; break;
    case 2: rgb[0] = p; rgb[1] = v; rgb[2] = t; break;
    case 3: rgb[0] = p; rgb[1] = q; rgb[2] = v; break;
    case 4: rgb[0] = t; rgb[1] = p; rgb[2] = v; break;
    default: rgb[0] = v; rgb[1] = p; rgb[2] = q; break;
  }
}

// ---- naming -----------------------------------------------------------------
//
// A COLOUR NEEDS A NAME because the inventory has to print something in a
// tooltip and "tunic #B4472A" is not it. Coarse on purpose: twelve hues, three
// lightness bands and a grey escape, which is the resolution somebody
// describing their own clothes actually uses. It is presentation only —
// nothing resolves a dye BY name — so it can be as lossy as it likes.
inline std::string DyeName(uint32_t dye) {
  if (!DyeSet(dye)) return "undyed";
  float c[3];
  DyeUnpack(dye, c);
  const float mx = c[0] > c[1] ? (c[0] > c[2] ? c[0] : c[2])
                               : (c[1] > c[2] ? c[1] : c[2]);
  const float mn = c[0] < c[1] ? (c[0] < c[2] ? c[0] : c[2])
                               : (c[1] < c[2] ? c[1] : c[2]);
  const float d = mx - mn;
  if (d < 0.08f) {
    if (mx < 0.2f) return "black";
    if (mx < 0.45f) return "charcoal";
    if (mx < 0.75f) return "grey";
    return "bleached";
  }
  // Hue in sixths, then the twelve names. Computed with the ordinary max-channel
  // form rather than atan2 so it costs nothing and cannot disagree with the
  // picker's own conversion at the boundaries.
  float h;
  if (mx == c[0]) h = (c[1] - c[2]) / d;
  else if (mx == c[1]) h = 2.0f + (c[2] - c[0]) / d;
  else h = 4.0f + (c[0] - c[1]) / d;
  h = h / 6.0f;
  if (h < 0.0f) h += 1.0f;
  static const char* kHue[12] = {"red",    "rust",   "amber", "gold",
                                 "green",  "moss",   "teal",  "sky",
                                 "blue",   "indigo", "plum",  "rose"};
  const char* hue = kHue[(int)(h * 12.0f) % 12];
  // Lightness and saturation qualify the hue rather than replacing it, so a
  // washed-out pale blue and a deep one are told apart without twenty-four more
  // names. Returned BY VALUE: the obvious `static std::string` trick makes this
  // header unusable from two threads and from two call sites in one printf,
  // which is exactly how a tooltip ends up naming the wrong garment.
  std::string s;
  if (mx < 0.35f) s = "dark ";
  else if (mx > 0.85f && d < 0.4f) s = "pale ";
  s += hue;
  return s;
}
