#!/usr/bin/env bash
# Validate every WGSL shader the way the engine actually compiles it.
#
# LoadShader() (src/gpu/resources.cpp) prepends common.wgsl to each shader before
# handing it to Dawn, so common.wgsl is NOT a standalone module and the others do
# not compile alone. We reproduce that concatenation, run tint --validate over the
# result, and remap reported line numbers back to the real file.
#
# Usage: bash scripts/check_shaders.sh [file.wgsl ...]
#   With no arguments, validates all shaders in assets/shaders.
#   Exits non-zero if any shader fails.

set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHADER_DIR="$ROOT/assets/shaders"
COMMON="$SHADER_DIR/common.wgsl"
WORLD_H="$ROOT/src/sim/world.h"

# Locate the tint CLI. Built by the `tint_cmd_tint_cmd` target once
# TINT_BUILD_CMD_TOOLS is ON; may land in a few places depending on generator.
find_tint() {
  if [ -n "${TINT:-}" ] && [ -x "$TINT" ]; then echo "$TINT"; return 0; fi
  local c
  for c in \
    "$ROOT/build/_deps/dawn-build/Release/tint.exe" \
    "$ROOT/build/_deps/dawn-build/src/tint/Release/tint.exe" \
    "$ROOT/build/_deps/dawn-build/src/tint/cmd/tint/Release/tint.exe" \
    "$ROOT/build/Release/tint.exe"; do
    [ -x "$c" ] && { echo "$c"; return 0; }
  done
  c="$(find "$ROOT/build" -name 'tint.exe' -type f 2>/dev/null | head -1)"
  [ -n "$c" ] && { echo "$c"; return 0; }
  return 1
}

TINT_BIN="$(find_tint)" || {
  cat >&2 <<'EOF'
check_shaders: tint CLI not found.

Build it once (TINT_BUILD_CMD_TOOLS is ON in CMakeLists.txt):
  cmake -S . -B build -G "Visual Studio 17 2022" -A x64
  cmake --build build --config Release --target tint_cmd_tint_cmd

Or point TINT=/path/to/tint.exe at an existing binary.
EOF
  exit 127
}

[ -f "$COMMON" ] || { echo "check_shaders: missing $COMMON" >&2; exit 1; }
[ -f "$WORLD_H" ] || { echo "check_shaders: missing $WORLD_H" >&2; exit 1; }

# Reproduce ShaderConstantPrelude() (src/gpu/resources.cpp): the world constants
# are generated from world.h, not declared in common.wgsl. Values are scraped
# from world.h rather than duplicated here, so this script cannot drift from the
# engine the way common.wgsl used to drift from world.h.
cpp_const() {  # cpp_const <name> -> literal, minus any type suffix
  sed -n "s/.*constexpr[a-z0-9_ ]* $1 = \([0-9.]*\)f\?;.*/\1/p" "$WORLD_H" | head -1
}
cpp_const_hex() {  # cpp_const_hex <name> -> hex literal, minus the u suffix
  sed -n "s/.*constexpr[a-z0-9_ ]* $1 = \(0x[0-9A-Fa-f]*\)u\?;.*/\1/p" "$WORLD_H" | head -1
}
W_N="$(cpp_const kWorldN)"
W_CHUNK="$(cpp_const kChunk)"
W_VOX="$(cpp_const kVoxelMeters)"
W_IFAIR="$(cpp_const_hex kCellOpIfAir)"
W_FAR="$(cpp_const kFarLevels)"
if [ -z "$W_N" ] || [ -z "$W_CHUNK" ] || [ -z "$W_VOX" ] || [ -z "$W_IFAIR" ] \
   || [ -z "$W_FAR" ]; then
  echo "check_shaders: cannot parse kWorldN/kChunk/kVoxelMeters/kCellOpIfAir/kFarLevels from $WORLD_H" >&2
  exit 1
fi
W_NCHUNK=$((W_N / W_CHUNK))

# Stain palette base — kStainPaletteBase is defined as an expression in world.h
# (kMaterialSlots - 8), so scrape the slot count and redo the arithmetic here
# rather than trying to parse the expression.
W_MATSLOTS="$(cpp_const kMaterialSlots)"
[ -n "$W_MATSLOTS" ] || {
  echo "check_shaders: cannot parse kMaterialSlots from $WORLD_H" >&2; exit 1; }
W_STAINBASE=$((W_MATSLOTS - 8))

# far-field grid (decoupled from the window — see world.h kFarN/kFarShiftBase)
W_FARN="$(cpp_const kFarN)"
[ -n "$W_FARN" ] || { echo "check_shaders: cannot parse kFarN from $WORLD_H" >&2; exit 1; }
W_FARNCHUNK=$((W_FARN / W_CHUNK))
W_FARSHIFT=0
while [ $((W_FARN << W_FARSHIFT)) -lt "$W_N" ]; do W_FARSHIFT=$((W_FARSHIFT + 1)); done

W_SHIFT=0
while [ $((1 << W_SHIFT)) -lt "$W_CHUNK" ]; do W_SHIFT=$((W_SHIFT + 1)); done
PRELUDE_TEXT="$(printf '%s\n' \
  "const WORLD_N : u32 = ${W_N}u;" \
  "const CHUNK : u32 = ${W_CHUNK}u;" \
  "const NCHUNK : u32 = ${W_NCHUNK}u;" \
  "const NUM_CHUNKS : u32 = $((W_NCHUNK * W_NCHUNK * W_NCHUNK))u;" \
  "const CHUNK_VOL : u32 = $((W_CHUNK * W_CHUNK * W_CHUNK))u;" \
  "const CHUNK_SHIFT : u32 = ${W_SHIFT}u;" \
  "const CHUNK_MASK : i32 = $((W_CHUNK - 1));" \
  "const WORLD_MASK : i32 = $((W_N - 1));" \
  "const NCHUNK_MASK : i32 = $((W_NCHUNK - 1));" \
  "const CELLOP_IF_AIR : u32 = ${W_IFAIR}u;" \
  "const STAIN_PALETTE_BASE : u32 = ${W_STAINBASE}u;" \
  "const FAR_LEVELS : u32 = ${W_FAR}u;" \
  "const FAR_N : u32 = ${W_FARN}u;" \
  "const FAR_NCHUNK : u32 = ${W_FARNCHUNK}u;" \
  "const FAR_NUM_CHUNKS : u32 = $((W_FARNCHUNK * W_FARNCHUNK * W_FARNCHUNK))u;" \
  "const FAR_VOX : u32 = $((W_FARN * W_FARN * W_FARN))u;" \
  "const FAR_MASK : i32 = $((W_FARN - 1));" \
  "const FAR_NCHUNK_MASK : i32 = $((W_FARNCHUNK - 1));" \
  "const FAR_SHIFT_BASE : u32 = ${W_FARSHIFT}u;" \
  "const VOXEL_METERS : f32 = ${W_VOX};")"

# LoadShader() also prepends the tuning constants (TuningWgslBlock, from
# assets/materials/tuning.json). Generated by a helper rather than re-parsed
# here, so bash never has to know the schema.
TUNING_TEXT="$(python "$ROOT/scripts/tuning_prelude.py")" || {
  echo "check_shaders: scripts/tuning_prelude.py failed" >&2
  exit 1
}
PRELUDE_TEXT="$(printf '%s\n%s' "$PRELUDE_TEXT" "$TUNING_TEXT")"

# Lines contributed ahead of the body: prelude + its "\n" + common + its "\n".
# Error line L in the combined source maps to line L - OFFSET in the body file.
COMMON_LINES="$(wc -l < "$COMMON" | tr -d ' ')"
PRELUDE_LINES="$(printf '%s\n' "$PRELUDE_TEXT" | wc -l | tr -d ' ')"
OFFSET=$((PRELUDE_LINES + 1 + COMMON_LINES + 1))

if [ "$#" -gt 0 ]; then
  FILES=("$@")
else
  FILES=()
  for f in "$SHADER_DIR"/*.wgsl; do
    [ "$(basename "$f")" = "common.wgsl" ] && continue
    FILES+=("$f")
  done
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

failed=0
checked=0

for f in "${FILES[@]}"; do
  name="$(basename "$f")"

  # A bare common.wgsl argument (e.g. from the edit hook) means "revalidate
  # everything", since every shader embeds it.
  if [ "$name" = "common.wgsl" ]; then
    exec bash "$ROOT/scripts/check_shaders.sh"
  fi

  [ -f "$f" ] || { echo "check_shaders: no such file: $f" >&2; failed=1; continue; }

  combined="$TMP/$name"
  { printf '%s\n\n' "$PRELUDE_TEXT"; cat "$COMMON"; printf '\n'; cat "$f"; } > "$combined"

  # `-f wgsl` parses, resolves, and validates, then re-emits WGSL we discard.
  # (`-f none` is advertised in --help but rejected by this build.) A missing
  # entry point is a real error here: every shader in this project has one.
  if out="$("$TINT_BIN" -f wgsl "$combined" 2>&1 >/dev/null)" && [ -z "$out" ]; then
    checked=$((checked + 1))
  else
    failed=1
    echo "FAIL $name"
    # tint reports "<path>:LINE:COL error: msg" against the combined file. Rewrite
    # the path to the real shader and subtract the common.wgsl prologue so line
    # numbers point where the user can actually edit. Diagnostics at or above the
    # offset came from common.wgsl itself and are labelled as such.
    printf '%s\n' "$out" | awk -v off="$OFFSET" -v real="$f" -v common="$COMMON" '
      # Match a trailing :LINE:COL after any path (handles C:/... drive letters).
      match($0, /:[0-9]+:[0-9]+/) {
        head = substr($0, 1, RSTART - 1)          # the path
        loc  = substr($0, RSTART + 1, RLENGTH - 1) # LINE:COL
        tail = substr($0, RSTART + RLENGTH)        # " error: msg"
        split(loc, p, ":")
        lineno = p[1] + 0
        if (lineno > off) printf "  %s:%d:%s%s\n", real, lineno - off, p[2], tail
        else              printf "  %s:%d:%s%s (via common.wgsl)\n", common, lineno, p[2], tail
        next
      }
      { print "  " $0 }
    '
  fi
done

if [ "$failed" -eq 0 ]; then
  echo "check_shaders: ${checked} shader(s) OK"
fi
exit "$failed"
