# build_info.cmake — run at BUILD time (cmake -P) by the sandvox_build_info
# target, so the commit an exe reports is the commit it was built from, not the
# one the build dir was last configured at.
#
# Why it exists: a determinism fingerprint (--fingerprint, DESIGN.md §14 risk 3)
# is compared across machines, and two hash sequences only mean something side
# by side when they came from the same source. "-dirty" marks a tree with
# uncommitted TRACKED changes — untracked files are ignored (this repo's root
# is full of screenshots) and so is everything under assets/ that the exe reads
# at runtime: the fingerprint records the asset stamps separately.
#
# Writes OUT only when the text changes, so an unchanged commit costs no
# recompile.
#   cmake -DSRC=<repo root> -DOUT=<generated .cpp> -P build_info.cmake
execute_process(COMMAND git -C "${SRC}" rev-parse --short=12 HEAD
                OUTPUT_VARIABLE _commit OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0 OR _commit STREQUAL "")
  set(_commit "unknown")
else()
  execute_process(COMMAND git -C "${SRC}" status --porcelain --untracked-files=no -- src CMakeLists.txt
                  OUTPUT_VARIABLE _dirty OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  if(NOT _dirty STREQUAL "")
    set(_commit "${_commit}-dirty")
  endif()
endif()
set(_text "// GENERATED by cmake/build_info.cmake at build time. Do not edit.\nconst char* SandvoxBuildCommit() { return \"${_commit}\"; }\n")
set(_old "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _text)
  file(WRITE "${OUT}" "${_text}")
endif()
